### ISSUE TITLE
[BUG] Cannot install

### ISSUE THREAD

**Issue by Freed-Wu** [weirongxu/coc-markdown-preview-enhanced#18] opened 2022-11-02 14:46 UTC
**Describe the bug**

```
Using npm from: /usr/bin/npm
Get info from https://registry.npmjs.org/
Downloading from https://registry.npmjs.org/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.4.4.tgz
Download progress 60.0%
Download progress 100.0%
Extension download at /home/wzy/.config/coc/extensions/node_modules/coc-markdown-preview-enhanced-dd990ab3-bf7b-4af4-970d-83b3970ebd17
Installing dependencies by: /usr/bin/npm install --ignore-scripts --no-lockfile --omit=dev --legacy-peer-deps --no-global.
[npm stderr] npm ERR! code ETARGET
[npm stderr] npm ERR! notarget No matching version found for @raidou/eslint-config-base@^1.6.0.
[npm stderr] npm ERR! notarget In most cases you or one of your dependencies are requesting
[npm stderr] npm ERR! notarget a package version that doesn't exist.
[npm stderr]
[npm stderr] npm ERR! A complete log of this run can be found in:
[npm stderr] npm ERR!     /home/wzy/.npm/_logs/2022-11-02T14_43_08_727Z-debug-0.log
/usr/bin/npm install exited with 1
```

```
❯ has node npm
✓ node 19.0.0
✓ npm 8.19.2
```

**Comment by weirongxu** [comment] 2022-11-02 18:00
Do you have something configured in ~/.npmrc?
Because when npm execute via `npm install --omit=dev`, these development dependencies shouldn't be installed.
And this package is also released in this version, so it shouldn't not matching.

https://www.npmjs.com/package/@raidou/eslint-config-base

Perhaps there is another registry url or proxy configured in .npmrc

**Comment by weirongxu** [comment] 2022-11-02 18:09
I used the same version of node and npm with the latest version of coc.nvim and couldn't reproduce it

**Comment by Freed-Wu** [comment] 2022-11-03 05:30
> Do you have something configured in ~/.npmrc?

```
registry=https://registry.npm.taobao.org/
```

**Comment by Freed-Wu** [comment] 2022-11-03 05:47
After comment npmrc, it works:

```
- ✓ coc-markdown-preview-enhanced Updated to v0.4.4
```

**Closed as completed** 2022-11-03 05:48 UTC
Labels: bug
