### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by theFG1998** [weirongxu/coc-markdown-preview-enhanced#19] opened 2023-01-02 08:58 UTC
**Describe the bug**
notarget No matching version found for @raidou/eslint-config-base@^1.6.0.

**Result from CocInfo**
## versions

vim version: NVIM v0.8.1
node version: v18.12.1
coc.nvim version: 0.0.82-b11a93ba 2022-12-25 15:19:13 +0800
coc.nvim directory: /Users/fgui/.local/share/nvim/plugged/coc.nvim
term: xterm-kitty
platform: darwin

## Log of coc.nvim

2023-01-02T16:54:52.613 INFO (pid:55904) [plugin] - coc.nvim initialized with node: v18.12.1 after 105
2023-01-02T16:54:52.802 INFO (pid:55904) [attach] - receive notification: highlight []
2023-01-02T16:54:52.888 INFO (pid:55904) [extension-installer] - Fetched info of coc-markdown-preview-enhanced {
  'dist.tarball': 'https://registry.npmmirror.com/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.4.4.tgz',
  'engines.coc': '^0.0.80',
  version: '0.4.4',
  name: 'coc-markdown-preview-enhanced'
}
2023-01-02T16:54:53.135 INFO (pid:55904) [model-download] - Download completed: URL {
  href: 'https://registry.npmmirror.com/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.4.4.tgz',
  origin: 'https://registry.npmmirror.com',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmmirror.com',
  hostname: 'registry.npmmirror.com',
  port: '',
  pathname: '/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.4.4.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2023-01-02T16:54:53.137 INFO (pid:55904) [model-download] - Downloaded https://registry.npmmirror.com/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.4.4.tgz => /Users/fgui/.config/coc/extensions/node_modules/coc-markdown-preview-enhanced-dcb0d5d1-f101-4e50-a7db-a13b775c4e8b
2023-01-02T16:55:26.753 ERROR (pid:55904) [extensions-index] - Error on install coc-markdown-preview-enhanced Error: /opt/homebrew/bin/npm install exited with 1
    at ChildProcess.<anonymous> (/Users/fgui/.local/share/nvim/plugged/coc.nvim/build/index.js:227:90972)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
2023-01-02T16:55:30.048 INFO (pid:55904) [attach] - receive notification: highlight []
2023-01-02T16:55:31.311 INFO (pid:55904) [attach] - receive notification: highlight []
2023-01-02T16:55:33.866 INFO (pid:55904) [attach] - receive notification: highlight []
2023-01-02T16:55:40.580 INFO (pid:55904) [attach] - receive notification: highlight []
2023-01-02T16:55:58.008 INFO (pid:55904) [attach] - receive notification: highlight []

**Steps to reproduce**
1. execute `nvim`
2. `:Cocinstall  coc-markdown-preview-enhanced`
3. See error

**Screenshots**
<img width="1174" alt="Screenshot 2023-01-02 at 00 23 03" src="https://user-images.githubusercontent.com/66351806/210210840-b488c6b1-f4a8-4a62-a410-72a9115639ea.png">

.npmrc
<img width="1173" alt="Screenshot 2023-01-02 at 00 23 47" src="https://user-images.githubusercontent.com/66351806/210210858-79a65d22-2c4b-4c97-bc7a-c45beff23924.png">

**Comment by weirongxu** [comment] 2023-01-02 09:00
Duplicate of #18

**Comment by theFG1998** [comment] 2023-01-02 09:11
> Duplicate of #18

solved, my newwork issue

**Closed as completed** 2023-01-02 09:13 UTC
Labels: bug
